version: "3.9"
services:
  firebase:
    build: .
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./emulator_data:/emulator_data
    ports:
      - 4000:4000
      - 4400:4400
      - 5001:5001
      - 8000:8000
      - 9000:9000
      - 9099:9099
    command: firebase emulators:start --export-on-exit=./emulator_data --import=./emulator_data
